import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';
import Head from 'next/head';

const UserSettings: NextPage = () => {
  const { data: session } = useSession();
  
  return (
    <div>
      <Head>
        <title>{session?.user?.name ? session.user.name : 'Anket Settings'}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>settings</div>
      </div>
  );
};

export default UserSettings;
// 