import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { SessionProvider } from 'next-auth/react';
import Login from '../components/Login';
import ThemeSwitcher from '../components/ThemeSwitcher';
import {
  AppShell,
  Burger,
  ColorScheme,
  ColorSchemeProvider,
  Group,
  Header,
  Image,
  MantineProvider,
  MediaQuery,
  Navbar,
} from '@mantine/core';
import { useState } from 'react';
import { QueryClient, QueryClientProvider } from 'react-query';
import { ReactQueryDevtools } from 'react-query/devtools'
import AppNavbar from '../components/AppNavbar';
import ContentMaxWidth from '../components/ContentMaxWidth';
import Head from 'next/head';

function MyApp({ Component, pageProps: { session, ...pageProps } }: AppProps) {
  const [opened, setOpened] = useState(false);
  const queryClient = new QueryClient();
  const [colorScheme, setColorScheme] = useState<ColorScheme>('light');
  const toggleColorScheme = (value?: ColorScheme) =>
    setColorScheme(value || (colorScheme === 'dark' ? 'light' : 'dark'));

  return (
    <QueryClientProvider client={queryClient}>
      <Head>
        <title>Anket - Easy Surveys</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SessionProvider session={session}>
        <ColorSchemeProvider
          colorScheme={colorScheme}
          toggleColorScheme={toggleColorScheme}
        >
          <MantineProvider
            withGlobalStyles
            withNormalizeCSS
            theme={{ colorScheme }}
          >
            <AppShell
              navbarOffsetBreakpoint='sm'
              asideOffsetBreakpoint='sm'
              fixed
              navbar={
                <Navbar
                  p='md'
                  hiddenBreakpoint='sm'
                  hidden={!opened}
                  width={{ sm: 200, lg: 300 }}
                >
                  <Navbar.Section grow mt='xs'>
                    <AppNavbar closeNavbar={() => setOpened(false)} />
                  </Navbar.Section>
                  <Navbar.Section>
                    <Login />
                  </Navbar.Section>
                </Navbar>
              }
              header={
                <Header height={70} p='md'>
                  <Group
                    align='center'
                    sx={{ justifyContent: 'space-between' }}
                  >
                    <MediaQuery largerThan='sm' styles={{ display: 'none' }}>
                      <Burger
                        opened={opened}
                        onClick={() => setOpened((o) => !o)}
                        size='sm'
                        mr='xl'
                      />
                    </MediaQuery>
                    <Image
                      src={
                        colorScheme === 'dark'
                          ? '/logo/logo-v01.png'
                          : '/logo/logo-v01-black.png'
                      }
                      height='32px'
                      alt='Anket Logo'
                    />
                    <ThemeSwitcher />
                  </Group>
                </Header>
              }
            >
              <ContentMaxWidth>
                <Component {...pageProps} />
              </ContentMaxWidth>
            </AppShell>
          </MantineProvider>
        </ColorSchemeProvider>
      </SessionProvider>
      <ReactQueryDevtools />
    </QueryClientProvider>
  );
}

export default MyApp;
