import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import CreateSurvey from '../components/CreateSurvey';
import MakeRequest from '../components/MakeRequest';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MakeRequest />
      <CreateSurvey />
    </div>
  );
};

export default Home;
