import { Box } from '@mantine/core';
import type { NextPage } from 'next';
import { useSession } from 'next-auth/react';
import Head from 'next/head';
import LandingPage from '../components/LandingPage';


const Home: NextPage = () => {
  const { data: session } = useSession();

  if (!session) return <LandingPage />

  return (
    <Box>
      <Head>
        <title>Anket - Easy Surveys</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>hi</div>
    </Box>
  );
};

export default Home;
