# reference: https://lewiskori.com/blog/deploying-next-js-apps-to-a-vps-using-github-actions-and-docker/

name: Build and Deploy

# Trigger the workflow on push to main
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        require: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          DATABASE_URL: ${{ secrets.APP_DATABASE_URL }}
          DISCORD_ID: ${{ secrets.APP_DISCORD_ID }}
          DISCORD_SECRET: ${{ secrets.APP_DISCORD_SECRET }}
          GITHUB_ID: ${{ secrets.APP_GITHUB_ID }}
          GITHUB_SECRET: ${{ secrets.APP_GITHUB_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.APP_NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.APP_NEXTAUTH_URL }}
        with:
          name: c-ehrlich/anket/anket_docker_image
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          buildargs: DATABASE_URL,DISCORD_ID,DISCORD_SECRET,GITHUB_ID,GITHUB_SECRET,NEXTAUTH_SECRET,NEXTAUTH_URL
          tags: latest

      - name: Deploy package to VPS
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          # github_token is created automatically by Github Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATABASE_URL: ${{ secrets.APP_DATABASE_URL }}
          DISCORD_ID: ${{ secrets.APP_DISCORD_ID }}
          DISCORD_SECRET: ${{ secrets.APP_DISCORD_SECRET }}
          GITHUB_ID: ${{ secrets.APP_GITHUB_ID }}
          GITHUB_SECRET: ${{ secrets.APP_GITHUB_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.APP_NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.APP_NEXTAUTH_URL }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN, DATABASE_URL, DISCORD_ID, DISCORD_SECRET, GITHUB_ID, GITHUB_SECRET, NEXTAUTH_SECRET, NEXTAUTH_URL
          script: |
            docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull ghcr.io/c-ehrlich/anket/anket_docker_image:latest
            docker stop anket
            docker system prune -f
            docker run --name anket -dit -p 3105:3000 ghcr.io/c-ehrlich/anket/anket_docker_image:latest
